// oledsplash/gen.cpp — bake a single small 1bpp frog logo for the mono OLED
// splash, area-downsampled from the settled frame of the TFT splash animation
// (components/ui/src/splash_anim.cpp). One static frame, so the OLED build
// doesn't pull the whole 76 KB TFT strip.
//
// Build & run (the data lives behind CONFIG_PIXFROG_DISPLAY_TFT, and ui_internal.h
// wants an IDF header we stub out):
//
//   mkdir -p /tmp/s/driver && printf 'typedef void* i2c_master_bus_handle_t;\n'\
//     'typedef void* i2c_master_dev_handle_t;\n' > /tmp/s/driver/i2c_master.h
//   g++ -std=c++17 -DCONFIG_PIXFROG_DISPLAY_TFT -I/tmp/s -I../../components/ui/src \
//       gen.cpp ../../components/ui/src/splash_anim.cpp -o gen
//   ./gen [destW=64] [destH=45] > ../../components/ui/src/splash_oled.cpp
//
// Emits kFrogOled (1bpp MSB-first, stride = (W+7)/8) + frog_oled_{w,h,data}().

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>

namespace pixfrog::ui::detail {
int splash_anim_w();
int splash_anim_h();
int splash_anim_count();
const uint8_t* splash_anim_frame(int);
}  // namespace pixfrog::ui::detail
using namespace pixfrog::ui::detail;

static inline int src_px(const uint8_t* f, int stride, int x, int y) {
    return (f[y * stride + (x >> 3)] >> (7 - (x & 7))) & 1;
}

int main(int argc, char** argv) {
    const int DW = argc > 1 ? std::atoi(argv[1]) : 64;
    const int DH = argc > 2 ? std::atoi(argv[2]) : 45;
    const int w = splash_anim_w(), h = splash_anim_h();
    const int sstride = (w + 7) / 8;
    const uint8_t* f  = splash_anim_frame(splash_anim_count() - 1);

    const int dstride = (DW + 7) / 8;
    std::vector<uint8_t> out(static_cast<size_t>(dstride) * DH, 0);
    for (int dy = 0; dy < DH; ++dy) {
        for (int dx = 0; dx < DW; ++dx) {
            int sx0 = dx * w / DW, sx1 = (dx + 1) * w / DW;
            int sy0 = dy * h / DH, sy1 = (dy + 1) * h / DH;
            if (sx1 <= sx0) sx1 = sx0 + 1;
            if (sy1 <= sy0) sy1 = sy0 + 1;
            int on = 0, total = 0;
            for (int sy = sy0; sy < sy1; ++sy)
                for (int sx = sx0; sx < sx1; ++sx) {
                    on += src_px(f, sstride, sx, sy);
                    ++total;
                }
            // Majority-fill keeps strokes ~1px without dropping the thin ones.
            if (on > 0 && on * 2 >= total) out[dy * dstride + (dx >> 3)] |= (0x80 >> (dx & 7));
        }
    }

    std::printf("// GENERATED by tools/oledsplash/gen.cpp — do not edit.\n");
    std::printf("// Static 1bpp frog logo for the OLED splash, downsampled from the\n");
    std::printf("// settled TFT splash frame. MSB-first, stride = (w+7)/8.\n\n");
    std::printf("#include <stdint.h>\n\n");
    std::printf("namespace pixfrog::ui::detail {\n\n");
    std::printf("namespace {\n");
    std::printf("constexpr int kFrogOledW = %d;\n", DW);
    std::printf("constexpr int kFrogOledH = %d;\n", DH);
    std::printf("const uint8_t kFrogOled[%d * %d] = {\n", dstride, DH);
    for (int y = 0; y < DH; ++y) {
        std::printf("    ");
        for (int b = 0; b < dstride; ++b)
            std::printf("0x%02X, ", out[y * dstride + b]);
        std::printf("\n");
    }
    std::printf("};\n}  // namespace\n\n");
    std::printf("int frog_oled_w() { return kFrogOledW; }\n");
    std::printf("int frog_oled_h() { return kFrogOledH; }\n");
    std::printf("const uint8_t* frog_oled_data() { return kFrogOled; }\n\n");
    std::printf("}  // namespace pixfrog::ui::detail\n");
    return 0;
}
